keys:
- &my_key age1hmyfj4fr0dnq8209nfxjjq42edugkv8tal3gxyz2z03jj5ch2ggqsm55ks
- &vps01_key age1dc5hjh2fttdlpzq3uyq953ddkjsauh8gxqscv4ea9wsf5k28uyksds0rxw

creation_rules:
- path_regex: 'secrets/vps01/[^/]+\.(yaml|json|env|ini)$'
  key_groups:
  - age:
    - *my_key
    - *vps01_key
